### ISSUE TITLE
Recovered wallet but shows a balance of 0 KAS

### ISSUE THREAD

**Issue by ChaosLegionaire** [azbuky/kaspium_wallet#13]
After running into the error of sending I re-installed the Android app.

I recovered my wallet with the 24 word phrase. I can see all my transactions but it is saying my acct has a total balance of 0 KAS.

Does it take time for it to sync to the blockchain or something?

**Comment by ChaosLegionaire** [comment]
This can be closed. Resetting the phone seems to have forced it to sync or whatever the issue was.

**Comment by gardusis** [comment]
> After running into the error of sending I re-installed the Android app.
> 
> I recovered my wallet with the 24 word phrase. I can see all my transactions but it is saying my acct has a total balance of 0 KAS.
> 
> Does it take time for it to sync to the blockchain or something?

hello
you solved your problem?. I faced the same problem. I reinstalled the app and the account is empty

**Comment by azbuky** [comment]
On Android, change node from ⚙️ > Network > Kaspa Node > Add Node, use URL 38.242.139.17

An update will be released soon that will fix the connectivity issue

**Comment by azbuky** [comment]
Fixed in v0.3.0
