### ISSUE TITLE
Option to delete wallet 

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#21]
**Is your feature request related to a problem? Please describe.**
Option to delete wallet from wallets-list panel

**Describe the solution you'd like**
1. Touch and hold wallet to delete
2. Ask confirmation for deletion of the wallet

**Describe alternatives you've considered**
1. On wallet selector, swipe button with selected wallet to the right
(Like in mobile version of Telegram)
3. Ask confirmation for deletion of the wallet

**Additional context**
![msg986039694-55805](https://user-images.githubusercontent.com/88991407/233217550-ecff7e0a-adc8-4e7e-9a3d-d28897ef52dc.jpg)

**Comment by azbuky** [comment]
Already possible. Swipe left, select delete icon and confirm.
