### ISSUE TITLE
Add 24 word limit for "Import Secret Phrase" Screen

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#22]
**Describe the bug**
Add 24 words limit for "Import Secret Phrase" Screen input-box. (Add word count verification)

**To Reproduce**
1. Open Application
2. Logout / Switch wallet
3. Import wallet
4. Perform Boundary Value Analysis on seed-input box (enter more than 24 words).

**Expected behavior**
After 24-th word - lock seed-input box for new characters.
Optionally add pop-out "Seed length should be equal to 24 words."

**Screenshots**
![msg986039694-55806](https://user-images.githubusercontent.com/88991407/233220148-ab895f7a-169f-42c3-a621-25a80c7cc06e.jpg)

**Comment by azbuky** [comment]
Fixed in v0.3.0
