### ISSUE TITLE
Donation address should not be editable

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#23]
**Describe the bug**
Donation address should not be editable

**To Reproduce**
1. Open Application
2. Go to "Donate"
3. Try to modify "Donation" address

**Expected behavior**
Donation address field is not editable

**Screenshots**
![msg986039694-55808 (1)](https://user-images.githubusercontent.com/88991407/233221287-c3f0ee24-9cc4-42e9-a9bd-ba313c1601dd.jpg)

**Comment by azbuky** [comment]
Fixed in v1.0.1
