### ISSUE TITLE
Add In-App transaction and UTXO details view.

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#25]
**Is your feature request related to a problem? Please describe.**
Edge case - user want to check his transaction history details while being offline (not relying on browser).

**Describe the solution you'd like**
New Screen with:

Transaction ID
Transaction Amount / Value
Transaction fee (if executed)
Source address (copiable + QR-code)
Destination address (copiable + QR-code)
Balance before / after transaction (if executed)
Transaction status
QR-Code + link of transaction in explorer

**Screenshots**
![Picsart_23-04-20_06-15-59-844.jpg](https://user-images.githubusercontent.com/88991407/233249687-c1a064e3-f625-44a9-8f4e-d2b4f5f17e61.jpg)

**Comment by azbuky** [comment]
v1.1.0 shows transaction details.
