### ISSUE TITLE
Button text disappear on touch

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#29]
**Describe the bug**
Button text "Copy Address" disappear on touch 

**To Reproduce**
1. Open application
2. Go to "Receive"
3. Touch "Copy Address"

**Expected behavior**
Button text is not disappearing on touch.

**Screenshots**
![Picsart_23-04-20_07-25-05-775.jpg](https://user-images.githubusercontent.com/88991407/233258066-e07c325e-10b0-451f-a2c5-af1b2a5641ef.jpg)

**Comment by azbuky** [comment]
Fixed
