### ISSUE TITLE
Import wallet

### ISSUE THREAD

**Issue by InTeamLife** [azbuky/kaspium_wallet#3]
I can't import the web wallet because it asks for 24 seed phrases, I only have 12 words in the web wallet
![IMG_20230120_082818](https://user-images.githubusercontent.com/30119373/213623960-5c75f29f-9ecb-4449-b568-783f4e7f8f02.jpg)
![IMG_20230120_081204](https://user-images.githubusercontent.com/30119373/213623967-ff86fc69-698d-440b-befc-b2fe2a37220d.jpg)

**Comment by Mofect** [comment]
I have the same issue,  after I entered 12-word phrase combinations, no way to hide the keyboard and go to the next. https://postimg.cc/G9GxtBZf

**Comment by azbuky** [comment]
Only CLI compatible 24 word phrases are allowed.

This is an alpha version of the wallet. Create a new wallet to test it out, don't try to import your main wallets.

**Comment by azbuky** [comment]
Starting with v1.0.1 there is support for 12 word wallets
