### ISSUE TITLE
Missing translation for "change name" on "Wallet addresses list" screen.

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#39]
Missing translation for "change name" on "Wallet addresses list" screen.

**Describe the bug**
New utxo name is not being created according to selected language.
Hard-coded default String. 
Proper translation should be loaded from json file.

**To Reproduce**
1. Open application
2. Switch to any language, except English
2. make new transaction
3. Swipe left
4. Go to "3 dots"
4. Switch to "change" tab
5. Observe new "change entry" name not being translated

**Expected behavior**
Default "change" name should be loaded from json-file.

**Screenshots**

![Picsart_23-04-20_16-46-44-034.jpg](https://user-images.githubusercontent.com/88991407/233386083-472de6ef-a4a4-402d-9115-a3ab42f144fb.jpg)

**Comment by azbuky** [comment]
Fixed
