### ISSUE TITLE
Missing translation Strings for "Donate" and "Available"

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#40]
**Describe the bug**
Missing translation Strings for "Donate" and "Available"

**To Reproduce**
1. Open Application
2. Switch language to any except English
3. Swipe Left
4. Open "Donate"
5. Observe missing translation

**Expected behavior**
Proper Strings in json-file for translation
(Dynamically load translation)

**Screenshots**

![Error_Fix_1](https://user-images.githubusercontent.com/88991407/233449779-98c4badc-f91c-476f-96f7-6e38f8effe42.PNG)

**Comment by azbuky** [comment]
Fixed by #72
