### ISSUE TITLE
Add "Open in Blockchain Explorer" button for "Receive Address" from "Wallet Addresses" list

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#43]
**Describe the solution you'd like**

EDIT: Obsolete, now relates [to this issue.](https://github.com/azbuky/kaspium_wallet/issues/46)

Add "Open in blockchain explorer" button for "receive address" in "Wallet Addresses" list

**Describe alternatives you've considered**

Like in [this issue](https://github.com/azbuky/kaspium_wallet/issues/42).

**Comment by azbuky** [comment]
Closing in favor of #46
