### ISSUE TITLE
Option to delete Nodes from Node-List

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#44]
**Describe the solution you'd like**
Option to delete Nodes from Node-List

**Screenshot**
![dn](https://user-images.githubusercontent.com/88991407/233463473-6ba0de8a-7483-4ec9-84e7-36620a9ec27e.PNG)

**Comment by azbuky** [comment]
Swipe left any unselected node and hit the delete icon. (Deleting a selected node is not possible)
