### ISSUE TITLE
Donate panel should not have "Scan QR code" button

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#45]
**Describe the bug**
Donate panel should not have "Scan QR code" button

**To Reproduce**
1. Open application
2. Swipe right
3. Go to "Donate"
4. Observe "Scan QR code button"

**Expected behavior**
No "QR code" button

**Screenshots**
![don](https://user-images.githubusercontent.com/88991407/233464161-2fadf0e0-dbc1-4466-b8b9-77f91a66d4df.PNG)

**Comment by azbuky** [comment]
Fixed in v1.0.1
