### ISSUE TITLE
Wallet name could have any length

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#48]
**Describe the bug**
When creating wallet, there is no verification of wallet length.
Name does not fit at screen (entry).
(Boundary value analysis.)

**To Reproduce**
1. Exit existing wallet
2. Create new wallet with a long name.

**Expected behavior**
Return error "Could not create address, with length more than N symbols. Please, shorten wallet name"

**Screenshots**
![Capture555](https://user-images.githubusercontent.com/88991407/233475276-b382beaf-8eef-48b2-b6f7-3a6d085c3c9c.PNG)

**Comment by azbuky** [comment]
Fixed in v1.0.1
