### ISSUE TITLE
Creation of wallets with the same name is possible.

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#50]
**Describe the bug**
Creation of wallets with same name is possible.

**To Reproduce**
Create two wallets with same name

**Expected behavior**
Throw error "Wallet name is being used. Please, create wallet with another name."

**Screenshots**
![msg986039694-55948](https://user-images.githubusercontent.com/88991407/233485752-57fc71ca-aca0-454b-a1cd-0cc7572bd50a.jpg)

**Comment by azbuky** [comment]
This is by design. Users can choose to use same name for different wallets if they want, though it doesn't mean they should.
Wallets have an unique id that is used to distinguish between them internally.
