### ISSUE TITLE
Do not allow setting up simple passwords.

### ISSUE THREAD

**Issue by ghost** [azbuky/kaspium_wallet#55]
**Describe the bug**

Do not allow setting up simple passwords.

Password should match specific criteria, for example:

1. (+ = More than) 8+ symbols, 1+ capital letter, 1+ lowercase letter, 1+ symbol.
2. Not to be too long (Check boundaries)
3. Don't allow "specific" symbols in it (due to possible code injections)

**Comment by azbuky** [comment]
Users can decide for themselves how strong they want their password.
