### ISSUE TITLE
Seamless integration between Kaspium, KDX and Web Wallet

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#57]
**Describe the solution you'd like**

Solution like being used in Telegram. Authenticate your wallet on another device just by scanning QR-code

![image](https://user-images.githubusercontent.com/88991407/233628266-f78ce839-8b64-4601-9075-d1138f079a47.png)

**Comment by azbuky** [comment]
This is not possible atm, Kaspium uses 24 word seed phrases while KDX and Web Wallet use 12 words.
Also KDX/Web Wallet is in maintenance mode as KNG (next gen web wallet) will replace it soon.
Closing for now.
