### ISSUE TITLE
%1 showing when copying an address

### ISSUE THREAD

**Issue by coderofstuff** [azbuky/kaspium_wallet#6]
![47522445-EBC5-42CA-B8D2-651F48F7E557](https://user-images.githubusercontent.com/114628839/219171486-bd20c69c-4130-45d9-a07e-585c4a14221d.png)

OS: iOS - TestFlight

Replication:
1. Open Contacts
2. Click Copy icon for the KaspiumTeam
3. `%1 address copied` is shown

**Comment by HLXEasy** [comment]
This is already fixed, there are no "%1" placeholders anymore. At least at the moment... ;-)
