### ISSUE TITLE
rusty-kaspad connection behaviour

### ISSUE THREAD

**Issue by azazino3** [azbuky/kaspium_wallet#62]
rusty-kaspad behaviour

Tried to connect to local rusty-kaspad node, got this behaviour

Ran node with command "(cargo run --release --bin kaspad) 2>&1 | tee ~/rusty-kaspa.log"

![Capture](https://user-images.githubusercontent.com/88991407/233663943-4ce623be-2ee5-491c-857b-d7ed1e1147ae.PNG)

**Comment by azbuky** [comment]
Kaspium requires a Kaspa node with the utxo index enabled ( add --utxoindex to the node command)
