### ISSUE TITLE
Sending to self shows duplicate transactions

### ISSUE THREAD

**Issue by coderofstuff** [azbuky/kaspium_wallet#7]
![311CE8B7-8B4F-4207-80BF-001B1205C077](https://user-images.githubusercontent.com/114628839/219204491-c672dd3a-9560-467c-80e6-6dafba62475d.png)

OS: iOS - TestFlight

Expectation: only the transaction with “#This Wallet” should be shown

**Comment by azbuky** [comment]
This is on purpose, to be in line with how KDX/web wallet shows similar txs.

![Screenshot from 2023-02-17 11-00-12](https://user-images.githubusercontent.com/567277/219600335-8ca9cd7e-0f34-4648-987e-10c4baaaca46.png)

**Comment by azbuky** [comment]
v1.1.0 changes this to a single entry with an up/down arrow icon symbolising it's a same wallet transaction
