### ISSUE TITLE
Dear, I have a issue with my address in my kaspium wallet. In my kaspium wallet app (android) by confusión I added a new address in my wallet, and now I can not access to my KAS asset accumulated in previous address. Please could you inform to me what is the process or instructions to revovery this asset, to transfer it to another kas wallet. Thanks.

### ISSUE THREAD

**Issue by SebasGC77** [azbuky/kaspium_wallet#81]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Android 13]
 - Device: [e.g. Galaxy S20]
 - kaspium_wallet version: [e.g. 0.2.0]

**Additional context**

**Comment by azbuky** [comment]
What Kaspium version are you using?

**Comment by SebasGC77** [comment]
Versión 0.2.0, downloaded from this site.

**Comment by azbuky** [comment]
For version 0.2.0 go to ⚙️-> Network->Kaspa Node-> Add node URL 38.242.139.17 and select it.

There is also a new version 0.3.0 available that fixes the connectivity issue but can only be installed after v0.2.0 is uninstalled so you need to make sure you have your secret phrase saved before uninstalling the app from your phone, so you can import your wallet after the update.

**Comment by azbuky** [comment]
Google Play Store open beta - https://play.google.com/store/apps/details?id=io.kaspium.kaspiumwallet
APK - https://github.com/azbuky/kaspium_wallet/releases/tag/v0.3.0-beta

Installing from Play Store is recommended.

**Comment by SebasGC77** [comment]
Thank you for your support.
