### ISSUE TITLE
"App not installed as package appears to be invalid."

### ISSUE THREAD

**Issue by notbrycem** [azbuky/kaspium_wallet#82]
**Describe the bug**
Unable to re install app on android version 13.

**To Reproduce**
1. Uninstall the kaspium app,
2. Download the installer again from the github,
3. Try to run the installer,
4. Get "App not installed as package appears to
be invalid" message.

**Expected behavior**
I expected the app to re install.
**Screenshot**
![Screenshot_20230621_220427_Package installer](https://github.com/azbuky/kaspium_wallet/assets/121530216/8a45d0b6-576c-4074-bc9a-9c6e8388eba1)

**Desktop (please complete the following information):**
 - OS and version: [e.g. Android 13]
 - Device: [e.g. Galaxy S20]
 - kaspium_wallet version: [e.g. 0.2.0]

**Additional context**
No further context.

**Comment by azbuky** [comment]
This is likely because the APK signature changed between v0.2.0 and v0.3.0. Try to completely remove the old version before installing v0.3.0.

This article might help - https://www.maketecheasier.com/remove-leftover-files-android
