### ISSUE TITLE
Support using passphrase per BIP39

### ISSUE THREAD

**Issue by coderofstuff** [azbuky/kaspium_wallet#89]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for BIP39 passphrases (the 25th word)

**Describe the solution you'd like**
This can be added as an advanced switch during seed creation or seed import (hidden by default)

**Comment by azbuky** [comment]
Wallet import with BIP39 passphrase is available since v1.1.0

Create wallet with BIP39 passphrase is not planned.
