### ISSUE TITLE
send KASPA with value of xx DOLLAR

### ISSUE THREAD

**Issue by agang0311** [azbuky/kaspium_wallet#9]
the mobile wallet should have a function that it can send KASPAs with value of xx dollars. 

when user need to send xx dollar to other people, he can just set xx dollar in mobile wallet, and mobile wallet transfer DOLLAR value into KASPA mount automatically.

![Screenshot_20230304-125600](https://user-images.githubusercontent.com/126937486/222876832-55666252-699e-47b7-ad8e-b212570f0b07.png)

**Comment by TheMainlander** [comment]
Will there also be Pair information displayed, like KAS/BTC, etc?

**Comment by azbuky** [comment]
Available since v1.1.0, tap KAS icon in left side of amount field to switch to fiat
