### ISSUE TITLE
Support using 12-word seed phrases with Kaspa standard derivation paths

### ISSUE THREAD

**Issue by coderofstuff** [azbuky/kaspium_wallet#90]
**Is your feature request related to a problem? Please describe.**
We're moving to use 12-words as the default while still using `44'/111111'/0'/type/index` derivation paths. This will also allow it to support imports from other wallets that already implement this (OKX Web3 wallet for example).

**Describe the solution you'd like**
Add it as the default for new wallets created for Kaspium, but allow the user to specify 24 words if they still want to.

**Comment by coderofstuff** [comment]
@aspect tagging you here so you're aware of this feature request in Kaspium.

**Comment by azbuky** [comment]
Added in v1.1.1
