### ISSUE TITLE
Own node setup

### ISSUE THREAD

**Issue by btclinux** [azbuky/kaspium_wallet#91]
Hi! I want to use the wallet with my own node. But for some reason wallet do not showing some in/out transactions. Balance and utxo set is correct. Maybe I need some specific options in my node setup? I use only --utxoindex parameter. Thank you!

**Comment by azbuky** [comment]
Hi! Kaspium will detect wallet transactions while it is running but in order to show all transactions it needs access to api.kaspa.org
