### ISSUE TITLE
Cant get my Kaspium Wallet back using my 24 word phrase

### ISSUE THREAD

**Issue by Platinumx99** [azbuky/kaspium_wallet#93]
Hello, I tried to send kaspa from Uphold to my Kaspium Wallet Iphone version. After 10 hours still no deposit into the wallet. I looked online and one option was to reinstall the wallet which i did and i cant get it back. I get an error. I tried switching to phones internet to bypass the wifi and still no recovery after the 24 word phrase.

gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = node.kaspium.io, port = 54972, details: null, rawResponse: null, trailers: {})

I have 18000 kaspa in this wallet i cant get to. What are some options? Or am i just out.

**Comment by azbuky** [comment]
Hi! Try the following:
If you are logged into your wallet, log out from ⚙️->Log out/Switch Wallet
Create a new wallet (do not bother saving the secret phrase as it's just a temporary wallet)
Go to ⚙️->Network->Kaspa Node and add node URL "38.242.139.17" and select it.
Log out of this temp wallet and re-import your real wallet.

You also have the option to import your wallet into the CLI wallet, see https://wiki.kaspa.org/en/setting-up-a-cli-wallet

Can you please also check if you can load https://kaspium.io in your device browser. Thanks!

**Comment by Platinumx99** [comment]
Thanks azbuky! I replied to you in the discord 👍
