### ISSUE TITLE
[small] v1.0.1 is listed in Github "Tags"but not Github "Releases"

### ISSUE THREAD

**Issue by eylenburg** [azbuky/kaspium_wallet#95]
The 1.0.1 release can be found here: https://github.com/azbuky/kaspium_wallet/tags
But not here: https://github.com/azbuky/kaspium_wallet/releases

This means that for example Obtainium (https://github.com/ImranR98/Obtainium), a popular app for updating Android apps from Github and other sources, is not able to see version 1.0.1. Could you please publish v1.0.1 and all future releases as a Github "Release" as well?

**Comment by Leccho** [comment]
Been there since september...

**Comment by azbuky** [comment]
@eylenburg can you check that v1.1.1 is working as expected for you and reopen this issue if not. Thanks!

**Comment by eylenburg** [comment]
Yes, it works with Obtainium, thank you!
